<?php
/**
 * @file
 * Code for the GSB Feature Case Content Type feature.
 */

include_once 'gsb_feature_case_ct.features.inc';

function gsb_feature_case_ct_gsb_cmis_test_process_info() {
	return array(
    'case' => array(
      'callback' => 'gsb_feature_case_ct_cmis_import',
    ),
  );
}

function gsb_feature_case_ct_cmis_import($doc, $uuid) {

  global $user;
	
  dpm($doc);

  $url = gsb_cmis_api_getObjectURL('default', $doc);

  $query = new EntityFieldQuery();
  $query->fieldCondition('field_item_id', 'value', $uuid, '=')->range(0, 1);
  $entities = $query->execute();

  if (!empty($entities['node'])) {
    $nids = array_keys($entities['node']);
    $node = node_load(array_shift($nids));
  } else {
    $values = array(
      'type' => 'case',
      'uid' => $user->uid,
      'status' => 1,
      'comment' => 1,
      'promote' => 0,
    );
    $node = entity_create('node', $values);
  }

  $ewrapper = entity_metadata_wrapper('node', $node);

  $ewrapper->title->set($doc->properties['cm:title']);
  $ewrapper->field_item_id->set($uuid);

  $ewrapper->field_year->set($doc->properties['gsb:cwoPublicationYear']);
  $ewrapper->field_document_name->set($doc->properties['cmis:contentStreamFileName']);
  $ewrapper->field_description->set($doc->properties['cm:description']);
  if (!empty($url) && trim($url) != '') {
    $ewrapper->field_link_document->url->set($url);
  }
  $ewrapper->field_author->set(array_map('trim', explode(',', $doc->properties['cm:author'])));
  $ewrapper->field_permissions_statement->set($doc->properties['gsb:permisiionStatement']);
  if (!empty($doc->properties['gsb:cwoLinkAtHarvard']) && trim($doc->properties['gsb:cwoLinkAtHarvard']) != '') {
    $ewrapper->field_link_single->url->set($doc->properties['gsb:cwoLinkAtHarvard']);
  }
  $ewrapper->field_citation->set($doc->properties['gsb:cwoCitation']);

  $ewrapper->save();

	dpm('in gsb_feature_case_ct_cmis_import');
}
